### ISSUE TITLE
Support entity  farmework??

### ISSUE THREAD

**Issue by lanfengqi** [exceptionless/Foundatio.Repositories#13]
Foundatio.Repositories Support entity  farmework??

**Comment by niemyjski** [comment]
We do not currently support EF, only Elasticsearch. We would be willing to accept a PR for EF Core support (Please note that some of the interfaces have changed in the elastic5 branch and will be merged in down the road.

I'm going to close this for now, but feel free to vote on this with a 👍 or open a PR. Also, please feel free to join us on slack: https://slack.exceptionless.com/
