### ISSUE TITLE
ElasticRepository.OnDocumentsSavedAsync will only send notifications if there were saved docs

### ISSUE THREAD

**Issue by niemyjski** [exceptionless/Foundatio.Repositories#2]
There could be added documents, so should we also send out a Added ChangeType notification? I almost think that we should have an event handler for Documents Saved and DocumentsAdded that just handles notifications. This would ensure that it's always executed properly.

https://github.com/exceptionless/Foundatio.Repositories/blob/master/src/Elasticsearch/Repositories/ElasticRepositoryBase.cs#L280-L281

**Comment by ejsmith** [comment]
Pretty sure that if you send a new doc to the Save function then it will automatically route it to Add and send out an added notification.

**Comment by niemyjski** [comment]
Just confirmed with a test that we will call the event handlers, but an error will be thrown if the new doc doesn't have an id set.
